### ISSUE TITLE
[1pt] A potential way to remove IF statements in Requests

### ISSUE THREAD

**Issue by scasplte2** [Topl/Brambl-JS#13]

**Comment by hhs1234567890** [comment]
`function checkParams(params, keysList) {
    desParams = Object.entries(params)
    structuredArr = []
    desParams.forEach(function(keyPair){
        if(keyPair[1]===undefined||keyPair===null){
            throw new Error("A "+keyPair[0]+" key must be specified cant use undefined or null");
        }
        structuredArr.push(keyPair[0])
    })
    if(!params){
         throw new Error("A parameter object must be specified");

    }else{
        
        if(JSON.stringify(keysList.sort()) !== JSON.stringify(structuredArr.sort())){
            var key = ""
            keysList.forEach(function(keys){
                key += ", "+keys
            })
            console.log(key)
            throw new Error("Make Sure you filling all keys, keys you must fill are "+ key);
        }else{
            
        }
    }

}

var obj = {
    hello: "!23",

    s:"123"
};
checkParams(obj, ["hello", "by", "s"]);`
That should work I still have to implement it.

**Comment by scasplte2** [comment]
nicely done 👍

**Comment by hhs1234567890** [comment]
@scasplte2 the function is at 'src/modules/Requests.ts:61 and I use it in all the functions.

**Comment by scasplte2** [comment]
@hhs1234567890 lets talk about this after stand up today please
