### ISSUE TITLE
[2pt] Best practices regarding file structure in TS project

### ISSUE THREAD

**Issue by scasplte2** [Topl/Brambl-JS#14]

**Comment by hhs1234567890** [comment]
@scasplte2 From my research it looks like you put all of the interface definitions in a types directory and then export them out to the file that you plan on using them on.

**Comment by scasplte2** [comment]
ok, if you wouldn't mind showing me tomorrow I'd appreciate it.

**Comment by scasplte2** [comment]
@hhs1234567890 do you have sources that you can put in this issue so we can close it?

**Comment by hhs1234567890** [comment]
https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html Very Bare Bones but gets a general idea across, This one talks about file structure with webpack and babel https://github.com/Microsoft/TypeScript-React-Conversion-Guide#typescript-react-conversion-guide. And to the best of my knowledge, we got it right. @scasplte2

**Comment by scasplte2** [comment]
thanks @hhs1234567890 👍
