### ISSUE TITLE
[5pt] research wallet setup and integration with JS SDKs

### ISSUE THREAD

**Issue by scasplte2** [Topl/Brambl-JS#18]

**Comment by hhs1234567890** [comment]
- Webpack vs Browserify
           - https://www.freecodecamp.org/news/browserify-vs-webpack-b3d7ca08a0a9/
- Direct build into webpack (typescript config)
          - https://webpack.js.org/guides/typescript/
- Had to change certain packages that did not work in the Browser.
          - node's crypto to crypto-browserify
          -crypto.syncScrypt function is now run by scrypt-async package
          -node fetch to cross-fetch
          -blake2 is now blake2b
Also a couple of changes to the index file to get it to create a variable on the window.
@scasplte2

**Comment by scasplte2** [comment]
👍
