### ISSUE TITLE
[8pt] Resolve all errors found with ESLint

### ISSUE THREAD

**Issue by hhs1234567890** [Topl/Brambl-JS#21]
On the branch `strict_typing`, ESLint was added to ensure recommended best practices are followed. This results in a number of errors being found when running `npm run lint`

**Comment by hhs1234567890** [comment]
@scasplte2 I was looking at the pull request between the two strict typings branches and I think it will be easier to just merge mine directly into the main typescript branch because my changes were all built off of the changes you made to mine. In short, all of your changes are there it's just in a separate branch because I thought it would be easier to work on it if I had the mocha tests so I just cloned the test one and then copy-pasted your code into it, and made some changes.

**Comment by scasplte2** [comment]
@hhs1234567890 please do not continue to submit commits to a branch that you have already submitted for review.
![image](https://user-images.githubusercontent.com/1753335/84617536-e777c380-ae94-11ea-8c85-aa7a35429be0.png)
![image](https://user-images.githubusercontent.com/1753335/84617558-f5c5df80-ae94-11ea-842a-c080094951a4.png)


This makes it incredibly difficult for me to review your work and now I must spend additional time (on time of the time I've already spent fixing issues) to merge in the conflicting changes between your changes and mine. This is the exact reason I have continually asked you to use additional branches to do your work.
