### ISSUE TITLE
[1pt] Research chrome extension details

### ISSUE THREAD

**Issue by hhs1234567890** [Topl/Brambl-JS#25]
- general best practices
- project structure
- unit tests (browsers restrictions?)
- reqs for different publishing to chrome store

**Comment by hhs1234567890** [comment]
https://developer.chrome.com/extensions/getstarted this seems to be the way that chrome want us to go about making an extension. I am not sure if there is a way we could write the code and then just add it too all browsers but from the looks of it they are all at least going to have a different JSON file.
@scasplte2

**Comment by hhs1234567890** [comment]
@scasplte2 
This is regarding data storage. Here is the docs for the storage API i was thinking of using. From my research it looks like it also works in firefox and edge so that is definitely good. here is the docs https://developer.chrome.com/apps/storage

it looks like metamask uses LocalStorage https://medium.com/better-programming/use-localstorage-to-store-data-on-the-browser-d10f8363dd.  But from my research the chrome API seems like a much better option. 

Lastly for the chrome API there are two options the local and the synced storages. The main upside of the local is that from what I can tell there is not a quota. As I am sure you can imagine the sync one automatically syncs your data to your account so as long as it does not look like we are going to run out of space we should use the sync option. 
That it pretty much the extent of my knowledge on browser storage. Let me know if you have any questions.

**Comment by scasplte2** [comment]
@hhs1234567890 I actually think you don't want to use the sync option. Apologies for not reading this earlier but if you sync the keyfile you are basically giving an potential hacker access to that keyfile unknowingly. Even though it is encrypted, the best practice is not to distribute your keyfile. I believe this is why Metamask is using LocalStorage instead of the chrome api. 

Is it difficult to switch over to local storage instead?

**Comment by scasplte2** [comment]
Also, thank you for the information. The links are very helpful 👍

**Comment by hhs1234567890** [comment]
@scasplte2 I think it should not be too difficult to use localStorage also it would save me some time because the asynchronicity of the chrome API was causing me trouble.
